# Generated by Django 4.2.7 on 2023-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('education_requirements', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_or_compensation', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('application_instructions', models.TextField()),
                ('application_url_or_email', models.CharField(max_length=255)),
                ('benefits', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_description', models.TextField()),
                ('contact_information', models.TextField()),
                ('tags_or_keywords', models.CharField(max_length=255)),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('job_posting_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
